services:
  db:
    image: postgres:alpine
    container_name: koperasiKita-db
    environment:
      POSTGRES_DB: koperasi_kita_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kikiji123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d koperasi_kita_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: koperasiKita-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: koperasi_kita_db
      DB_USERNAME: postgres
      DB_PASSWORD: kikiji123
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
