spring.application.name=koperasiKita

# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/koperasi_kita
spring.datasource.username=postgres
spring.datasource.password=DhafinHalip@555
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.hibernate.ddl-auto=update