spring.application.name=koperasiKita

# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/koperasi_kita_db
spring.datasource.username=postgres
spring.datasource.password=kikiji123
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.hibernate.ddl-auto=update

# Swagger/OpenAPI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.csrf.enabled=false
